#CONFIG
app:
  version: 0.0.1
server:
  port: 9002 #puerto del servidor Tomcat  
  version: 0.0.1
  forward-headers-strategy: native
  ssl: #Configuracion HTTPS
    enabled: true
    key-store: classpath:AutoFirmV3Store.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: autofirmadov3
