# server:
#   port: ${app.security-server-port}
server:
  port: ${app.security-server-port}
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: geforex
    key-store-type: PKCS12
    key-alias: myCertLocal

spring:
  datasource:
    url: jdbc:oracle:thin:@${app.oracle-server-host}:${app.oracle-server-port}/${app.oracle-service-name}
    username: ${app.oracle-db-owner-name}
    password: ${app.oracle-db-password}
    driver-class-name: ${app.oracle-driver}
  jpa:
    show-sql: true
    hibernate:
      dialect: ${app.oracle-dialect}
      format: true
app:
  security:
    jwt:
      secret: askljdhfgenerarclaveconalgunaherramientacomokeypassasdasdggf
      expiration: 86400

eureka:
  client:
    serviceUrl:
      defaultZone: https://${app.eureka-server-host}:${app.eureka-server-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5
