server:
  port: ${app.security-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:${app.eureka-port}/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationInSeconds: 5